### PR TITLE
Adding an Options page

### PR DESCRIPTION
**Pull request by mbloomfi**
```
modified:   manifest.json
new file:   options.html
new file:   options.js
modified:   quni.js
```

"Adding an options page"

### CODE REVIEW

**Comment by mbloomfi** [comment]
This adds a ton of stuff. An options page, stored variables, the beginnings of the star wars theme (hidden for now) and a lot of bug fixes.

**Comment by mbloomfi** [comment]
The theme function now works but is hidden. Everything should be functional now.

**Comment by mcdonnez** [comment]
Cool stuff! I just merged it. How do you get the star wars theme to appear?

**Comment by mcdonnez** [comment]
Nevermind, found the hidden option.

**Comment by mcdonnez** [comment]
I'm going to play around with it a little bit and notice if there are any
bugs. I'll upload it in a couple of hours.

**Pull request merged**
